import { appConfig } from "./app-config";
import type { AreaDefinition, AreaSlug } from "../types";

export const areas: AreaDefinition[] = [
  {
    slug: "coordenacao-administrativa",
    title: "Coordenacao Administrativa",
    shortTitle: "Administrativa",
    route: "/gestao/coordenacao-administrativa",
    legacyRoute: "/areas/coordenacao-administrativa",
    description: "Nucleo executivo para prioridades, governanca, deliberacoes e visao consolidada.",
    purpose: "Pilotar o fluxo minimo com visao global, acompanhamento de pendencias e consolidacao institucional.",
    phase: "MVP",
    icon: "administrativa",
    driveUrl: "https://drive.google.com/drive/folders/1iA4gg8ON9d9seNzHuE1V3EoAbrSqdd5u",
    moduleEnabled: true,
    pilot: true,
    tabs: ["Visao executiva", "Plano de governanca", "Areas e liderancas", "Deliberacoes", "Documentos", "Comunicacao", "Riscos", "Reunioes", "Relatorios", "Historico"],
    highlights: ["Deliberacoes rastreaveis", "Pendencias criticas", "Fluxo mensal"]
  },
  {
    slug: "coordenacao-clinica",
    title: "Coordenacao Clinica",
    shortTitle: "Clinica",
    route: "/gestao/coordenacao-clinica",
    legacyRoute: "/areas/coordenacao-clinica",
    description: "Consolida protocolos, indicadores obrigatorios e riscos assistenciais.",
    purpose: "Receber o piloto de indicadores em leitura inicial e consolidar riscos clinicos.",
    phase: "MVP",
    icon: "clinica",
    driveUrl: "https://drive.google.com/drive/folders/1x3zNfPG6yu6jAG9aUCdPgIrRG0a19jGm",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Visao geral", "Indicadores", "Protocolos", "Riscos", "Relatorios"],
    highlights: ["Indicadores QMENTUM", "Protocolos clinicos", "Riscos assistenciais"]
  },
  {
    slug: "gestao-da-qualidade",
    title: "Gestao da Qualidade",
    shortTitle: "Qualidade",
    route: "/gestao/gestao-da-qualidade",
    legacyRoute: "/areas/gestao-da-qualidade",
    description: "Validacao independente, fila mensal e consolidacao do desempenho das areas.",
    purpose: "Validar entregas, evidencias e gerar relatorios mensais sem duplicar registros.",
    phase: "MVP",
    icon: "qualidade",
    driveUrl: "https://drive.google.com/drive/folders/1-9JJ1Mq1tFwV3rSh-JFuuADzUD2d6uxF",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Painel executivo", "Fila de validacao", "Grade mensal", "Relatorio mensal", "Auditoria"],
    highlights: ["Validacao independente", "Relatorio mensal", "Pontuacao com trilha"]
  },
  {
    slug: "gestao-de-pessoas",
    title: "Gestao de Pessoas",
    shortTitle: "Pessoas",
    route: "/gestao/gestao-de-pessoas",
    legacyRoute: "/areas/gestao-de-pessoas",
    description: "Capacitacao, composicao da equipe, participacao e politicas de pessoas.",
    purpose: "Gerenciar entregas de pessoas sem duplicar avaliacoes e dependencias operacionais.",
    phase: "MVP",
    icon: "pessoas",
    driveUrl: "https://drive.google.com/drive/folders/1Kjw9BLxRsPka3j6zYu5wQNW8HDWg-b24",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Visao geral", "Treinamentos", "Politicas", "Composicao", "Relatorios"],
    highlights: ["Treinamentos", "Composicao da equipe", "Politicas anuais"]
  },
  {
    slug: "gestao-de-equipamentos",
    title: "Gestao de Equipamentos",
    shortTitle: "Equipamentos",
    route: "/gestao/gestao-de-equipamentos",
    legacyRoute: "/areas/gestao-de-equipamentos",
    description: "Conformidade de equipamentos, manutencao e protocolos de suporte assistencial.",
    purpose: "Organizar controles estruturais e evidencias tecnicas por ciclo de revisao.",
    phase: "Fase 2",
    icon: "equipamentos",
    driveUrl: "https://drive.google.com/drive/folders/14D9O3T_LZ6t-NWvfqzsA_f3-dC-3EhX2",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Painel", "Manutencao", "Checklist", "Riscos", "Historico"],
    highlights: ["Checklist critico", "Planos corretivos", "Protocolos tecnicos"]
  },
  {
    slug: "gestao-de-conduta-etica",
    title: "Gestao de Conduta Etica",
    shortTitle: "Conduta Etica",
    route: "/gestao/gestao-de-conduta-etica",
    legacyRoute: "/areas/gestao-de-conduta-etica",
    description: "Fluxos eticos, codigo de conduta e tratamento de questoes sensiveis com sigilo.",
    purpose: "Restringir acessos e registrar deliberacoes eticas com auditoria forte.",
    phase: "Fase 2",
    icon: "etica",
    driveUrl: "https://drive.google.com/drive/folders/16t_3OJ6E_zUWqOJJXw_VLEkqFYPhOO3k",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Painel", "Fluxos eticos", "Documentos", "Casos", "Historico"],
    highlights: ["Acesso restrito", "Codigo de conduta", "Deliberacao formal"]
  },
  {
    slug: "gestao-financeira",
    title: "Gestao Financeira",
    shortTitle: "Financeira",
    route: "/gestao/gestao-financeira",
    legacyRoute: "/areas/gestao-financeira",
    description: "Acompanhamento rastreavel de dados financeiros autorizados e relatorios oficiais.",
    purpose: "Consolidar apenas dados autorizados, sem executar efeitos societarios automaticamente.",
    phase: "Fase 2",
    icon: "financeira",
    driveUrl: "https://drive.google.com/drive/folders/161vx6j_9TQsrB70KwPceb7MT7z2Tvp2s",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Painel", "Entradas oficiais", "Relatorios", "Pendencias", "Historico"],
    highlights: ["Fonte contabil oficial", "Rastreabilidade", "Controle de acesso"]
  },
  {
    slug: "gestao-operacional",
    title: "Gestao Operacional",
    shortTitle: "Operacional",
    route: "/gestao/gestao-operacional",
    legacyRoute: "/areas/gestao-operacional",
    description: "Fluxos operacionais, contingencias, barreiras e suporte institucional.",
    purpose: "Monitorar planos de contingencia e gargalos sem poluir a experiencia em smartphone.",
    phase: "Fase 2",
    icon: "operacional",
    driveUrl: "https://drive.google.com/drive/folders/17YO-OZKAXBHrfy3L3YTJRYCrZSXUegS7",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Visao geral", "Contingencias", "Barreiras", "Planos", "Riscos"],
    highlights: ["Contingencias", "Barreiras operacionais", "Mapa anual de riscos"]
  },
  {
    slug: "gestao-de-prontuario",
    title: "Gestao de Prontuario",
    shortTitle: "Prontuario",
    route: "/gestao/gestao-de-prontuario",
    legacyRoute: "/areas/gestao-de-prontuario",
    description: "Auditorias, conformidade documental e rastreio de nao conformidades sem dados sensiveis.",
    purpose: "Conduzir auditorias com foco em conformidade e planos corretivos sem expor dados identificaveis.",
    phase: "Fase 2",
    icon: "prontuario",
    driveUrl: "https://drive.google.com/drive/folders/1MrGjV7IqD0JZ2FRwxDflin7yshFHsepy",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Painel", "Auditorias", "Nao conformidades", "Treinamentos", "Historico"],
    highlights: ["Conformidade documental", "Reauditoria", "Treinamento vinculado"]
  },
  {
    slug: "ambulatorio-pre-anestesico",
    title: "Ambulatorio Pre-anestesico",
    shortTitle: "Ambulatorio",
    route: "/gestao/ambulatorio-pre-anestesico",
    legacyRoute: "/areas/ambulatorio-pre-anestesico",
    description: "Fluxo, estrutura, barreiras e auditorias do pre-atendimento anestesico.",
    purpose: "Acompanhar estrutura e qualidade documental, evitando duplicacao com Prontuarios.",
    phase: "Fase 2",
    icon: "ambulatorio",
    driveUrl: "https://drive.google.com/drive/folders/1AKLsTMs1Yo2fQbNLzHyOTkU7baoB1GhH",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Visao geral", "Estrutura", "Fluxo", "Auditorias", "Riscos"],
    highlights: ["Fluxo e barreiras", "Conciliacao", "TCLE"]
  },
  {
    slug: "extra-bloco",
    title: "Areas Assistenciais Extra Bloco",
    shortTitle: "Extra Bloco",
    route: "/gestao/extra-bloco",
    legacyRoute: "/areas/extra-bloco",
    description: "Gestao por setor assistencial com visao consolidada, dimensionamento e riscos.",
    purpose: "Permitir novos setores sem mudanca de codigo e consolidar mapas para a Coordenacao Clinica.",
    phase: "Fase 2",
    icon: "extra-bloco",
    driveUrl: "https://drive.google.com/drive/folders/1U7yNHwc9puMXVBl_vle5ma8otHh0fsf_",
    moduleEnabled: true,
    pilot: false,
    tabs: ["Consolidado", "Setores", "Dimensionamento", "Riscos", "Relatorios"],
    highlights: ["Setores configuraveis", "Dimensionamento", "Relatorio trimestral"]
  },
  {
    slug: "esg",
    title: "ESG",
    shortTitle: "ESG",
    route: "/gestao/esg",
    legacyRoute: "/areas/esg",
    description: "Modulo estrategico para iniciativas ESG, metas e relatorio anual quando ativado.",
    purpose: "Ficar oculto ate haver lideranca, escopo e pasta validos.",
    phase: "Fase 3",
    icon: "esg",
    moduleEnabled: appConfig.strategicModules.esg,
    pilot: false,
    tabs: ["Visao geral", "Iniciativas", "Indicadores", "Evidencias", "Relatorios"],
    highlights: ["Modulo configuravel", "Sem Drive inventado", "Ativacao administrativa"]
  },
  {
    slug: "inovacao",
    title: "Inovacao",
    shortTitle: "Inovacao",
    route: "/gestao/inovacao",
    legacyRoute: "/areas/inovacao",
    description: "Modulo estrategico para ideias, pilotos e incorporacao de melhorias quando ativado.",
    purpose: "Ficar oculto ate haver processo definido e instancias de parecer configuradas.",
    phase: "Fase 3",
    icon: "inovacao",
    moduleEnabled: appConfig.strategicModules.inovacao,
    pilot: false,
    tabs: ["Visao geral", "Ideias", "Pilotos", "Resultados", "Licoes"],
    highlights: ["Modulo configuravel", "Sem Drive inventado", "Pilotos homologados"]
  }
];

export const activeAreas = areas.filter((area) => area.moduleEnabled);

export const areaBySlug = activeAreas.reduce<Record<AreaSlug, AreaDefinition | undefined>>(
  (acc, area) => {
    acc[area.slug] = area;
    return acc;
  },
  {} as Record<AreaSlug, AreaDefinition | undefined>
);
